SELECT * FROM CITY 
WHERE CountryCode = 'USA' AND POPULATION > 100000;

SELECT DISTINCT CITY FROM STATION
WHERE ID % 2 = 0;

SELECT COUNT(CITY) - COUNT(DISTINCT CITY) FROM STATION;

SELECT DISTINCT CITY 
FROM STATION 
WHERE LEFT(CITY, 1) IN ('A', 'E', 'I', 'O', 'U', 'a', 'e', 'i', 'o', 'u');

